### ISSUE TITLE
自动布局不支持

### ISSUE THREAD

**Issue by laughingg** [LZAscott/ScottPageView#1]
使用自动布局的时候，图片会乱套.

**Comment by LZAscott** [comment]
这个倒是没有考虑。因为轮播图用的多的都是在顶部，屏幕宽度。就直接用frame写死的了。

**Comment by laughingg** [comment]
如果用 autolayout 不就傻眼了啊。 代码结构还可以优化一下。我依照你的代码写了个swift 版本吧的。支持 autolayout

**Comment by LZAscott** [comment]
如果是这样的话，我就先放一个view，然后这个view用autoLayout,然后把轮播图加在这个view上。
