### ISSUE TITLE
感谢分享, 相互学习, 共同进步.

### ISSUE THREAD

**Issue by guowilling** [LZAscott/ScottPageView#3]
我知道原因了，你看到位置局右的那个是通过xib创建的，那个没有适配屏幕。所以只支持代码方式创建。

**Comment by guowilling** [comment]
代码里是设置了居中的, 不知道是哪里布局出了点问题.

**Comment by guowilling** [comment]
很感谢分享, 我自己之前是用的 n + 2 个 ImageView 来实现的轮播, 感觉不够好, 看了下你的源码和文章, 很有收获.

**Comment by LZAscott** [comment]
应该是居中的呀。
